table '2. Report-Specific Objects'
	isHidden
	lineageTag: bc077534-c5b0-40dd-9fb4-4bad6abc2bd2

	measure Transparent =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			"#00000000"
		isHidden
		displayFolder: Control Colours
		lineageTag: 7af08448-2e99-4e55-a505-8e431865c8dd

	measure 'Sum (2022; Inverse)' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			-[Sum (PY)]
		formatString: #,##0; #,##0; #,##0
		isHidden
		displayFolder: Dynamic Format Strings
		lineageTag: 2ad4db16-6991-4157-8219-d80f6deb39ed

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Year Colour' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			IF(
			    SELECTEDVALUE( 'Table'[Year] ) = 2022,
			    "#ece6da",
			    "#737068"
			)
		isHidden
		displayFolder: Control Colours
		lineageTag: 7a633807-acfb-4667-bf5f-0f51cfe82c98

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Count (Format String)' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			[Count]
		isHidden
		displayFolder: Dynamic Format Strings
		lineageTag: a823e998-d1ef-493c-a9a7-8e843dc61fc9

		formatStringDefinition =
				VAR _Count = [Count]
				VAR _Symbol =
				    SWITCH(
				        TRUE( ),
				        _Count > 0, UNICHAR( 10008 ),
				        _Count = 0, UNICHAR( 10004 ),
				        BLANK( )
				    )
				RETURN
				    "#,##0 " & _Symbol

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Waffle Subtitle' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _Result = [Sum (% of PY YTD)]
			RETURN
			    "Progress: "
			        & FORMAT( _Result, "#,##0%" )
		isHidden
		displayFolder: Waffle Chart (DAX Unicode)
		lineageTag: fb2bb51a-f88a-49e0-b70d-2c8f9bfe8a11

	measure 'Dynamic Title (Color Indicator)' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _Result = [Sum (% of PY YTD)]
			VAR _Actuals = [Sum (CY YTD)]
			VAR _Color =
			    IF(
			        _Result < 1,
			        UNICHAR( 128308 ),
			        UNICHAR( 128309 )
			    )
			RETURN
			    _Color & " Actuals:"
			        & FORMAT( _Actuals, " #,##0,K" )
		isHidden
		displayFolder: Dynamic Titles
		lineageTag: 65c9248a-39c8-491d-87ce-125866b90de7

	measure 'Rating Subtitle' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _Rating = [Sum (% of PY YTD)] * 5
			RETURN
			    "Rating: " & FORMAT( INT( _Rating ), "#,##0" )
		isHidden
		displayFolder: Rating (DAX Unicode)
		lineageTag: 22a84017-ed7c-4e73-a82b-0982319caeab

	measure Waffle =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			-- Init
			VAR _Actuals = [Sum (CY YTD)]
			VAR _Target = [Sum (PY YTD)]
			VAR _Perc =
			    MIN( 1, DIVIDE( _Actuals, _Target ) )
			VAR _TotalCells = 100
			VAR _RowLength = 10
			VAR _TotalRows =
			    CEILING(
			        DIVIDE( _TotalCells, _RowLength ),
			        1
			    )
			VAR _FilledCount =
			    ROUND( _Perc * _TotalCells, 0 )
			
			-- Unicode characters
			VAR _Filled = UNICHAR( 9632 ) & " " -- ■
			VAR _Empty = UNICHAR( 9633 ) & " "  -- □
			-- Figure out the waffle Height x Width etc.
			VAR _FullFilledLines =
			        INT ( _FilledCount / _RowLength )
			VAR _FilledPartial =
			    MOD( _FilledCount, _RowLength )
			VAR _EmptyPartial =
			    _RowLength - _FilledPartial
			VAR _FullEmptyLines =
			    _TotalRows - _FullFilledLines
			        - IF( _FilledPartial > 0, 1, 0 )
			
			-- Result
			VAR _Waffle =
			    REPT(
			        REPT( _Empty, _RowLength )
			            & UNICHAR( 10 ),
			        _FullEmptyLines
			    )
			        & IF(
			            _FilledPartial > 0,
			            REPT( _Filled, _FilledPartial )
			                & REPT( _Empty, _EmptyPartial )
			                & UNICHAR( 10 ),
			            ""
			        )
			        & REPT(
			            REPT( _Filled, _RowLength )
			                & UNICHAR( 10 ),
			            _FullFilledLines
			        )
			RETURN
			    _Waffle
		isHidden
		displayFolder: Waffle Chart (DAX Unicode)
		lineageTag: 2ccd2bf1-9988-423e-abd0-12ccb403f7ae

	measure Rating =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			-- Init
			VAR _Actuals = [Sum (CY YTD)]
			VAR _Target = [Sum (PY YTD)]
			VAR _Perc =
			    MIN( 1, DIVIDE( _Actuals, _Target ) )
			VAR _MaxStars = 5
			VAR _FilledStarsCount =
			    INT( _Perc * _MaxStars )
			VAR _EmptyStarsCount =
			    _MaxStars - _FilledStarsCount
			
			
			-- Unicode characters
			VAR _FilledStar = UNICHAR( 9733 )         -- ★
			VAR _EmptyStar = UNICHAR( 9734 )          -- ☆
			-- Result
			VAR _StarRating =
			    REPT( _FilledStar, _FilledStarsCount )
			        & REPT( _EmptyStar, _EmptyStarsCount )
			RETURN
			    _StarRating & UNICHAR( 10 )
		isHidden
		displayFolder: Rating (DAX Unicode)
		lineageTag: 860209d7-5ea2-4a48-9ea1-2f9e7df39fce

	measure 'Dynamic Subtitle (Context)' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _Perc = [Sum (Δ% PY YTD)]
			VAR _Color =
			    "   ( "
			        & IF(
			            _Perc < 1,
			            UNICHAR( 9660 ),
			            UNICHAR( 9650 )
			        )
			VAR _Target = [Sum (PY YTD)]
			RETURN
			    "1 Year Prior: "
			        & FORMAT( _Target, "#,##0,K" )
			        & _Color
			        & FORMAT(
			            _Perc,
			            " #,##0.0%; #,##0.0%; #,##0%"
			        )
			        & " )"
		isHidden
		displayFolder: Dynamic Titles
		lineageTag: faf3bed7-a8d6-42b2-b0e4-edc35cd41bed

	measure '% Claims Approved' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _ApprovedClaims =
			    CALCULATE(
			        [Sum],
			        'Table'[Boolean Dimension] = "Approved"
			    )
			VAR _Perc = DIVIDE( _ApprovedClaims, [Sum] )
			RETURN
			    FORMAT( _Perc, "#,##0%" )
		isHidden
		displayFolder: KPI Doughnut
		lineageTag: e8761060-f832-42a7-8816-f806e256b7bd

	measure '# Claims Approved' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _ApprovedClaims =
			    CALCULATE(
			        [Sum],
			        'Table'[Boolean Dimension] = "Approved"
			    )
			RETURN
			    FORMAT( _ApprovedClaims, "#,##0,.0K" )
		isHidden
		displayFolder: KPI Bar
		lineageTag: 1778fef3-fdfe-49f2-806a-74e0ca8b7fc8

	measure 'KPI Bullet Subtitle' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _Increase = UNICHAR( 8599 )
			VAR _Decrease = UNICHAR( 8600 )
			VAR _Delta = [Sum (Δ PY YTD)]
			VAR _Arrow =
			    IF( _Delta > 0, _Increase, _Decrease )
			VAR _Result =
			    _Arrow & " "
			        & FORMAT( [Sum (Δ% PY YTD)], "#,##0%" )
			        & " vs. LY"
			RETURN
			    _Result
		isHidden
		displayFolder: Dynamic Titles
		lineageTag: 01eae849-d1a7-49ec-9afd-af6363015ed4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI Bullet Title' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _Goblins =
			    CALCULATE(
			        [Sum],
			        'Table'[Boolean Dimension] = "Approved"
			    )
			RETURN
			    FORMAT( _Goblins, "#,##0,.0K" )
			        & " Approved Claims"
		isHidden
		displayFolder: Dynamic Titles
		lineageTag: 72cf28a2-c0bd-4d61-9e8e-591de15c40f4

	measure 'Sum (Latest Data Point)' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			
			VAR _LatestDate =
			    CALCULATE(
			        MAX( 'Table'[Month] ),
			        REMOVEFILTERS( )
			    )
			VAR _LatestMonth = MONTH( _LatestDate )
			VAR _LatestYear = YEAR( _LatestDate )
			RETURN
			    CALCULATE(
			        [Sum],
			        'Date'[Month (MM)] = _LatestMonth,
			        'Date'[Year (YYYY)] = _LatestYear
			    )
		isHidden
		displayFolder: KPI Trend
		lineageTag: 421c52e3-3109-4681-a6e4-b4c41c09908d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI Trend Line Title' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			FORMAT(
			    [Sum (Latest Data Point)],
			    "#,##0,.0K"
			) & " Claims"
		isHidden
		displayFolder: Dynamic Titles
		lineageTag: 5a737d28-fd3a-4785-bdcd-52e8904a178a

	measure 'KPI Trend Line Subtitle' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			
			VAR _LatestDate =
			    CALCULATE(
			        MIN( 'Table'[Month] ),
			        VALUES( 'Date'[Year (YYYY)] ),
			        REMOVEFILTERS( )
			    )
			VAR _LatestMonth = MONTH( _LatestDate )
			VAR _LatestYear = YEAR( _LatestDate )
			VAR _Start =
			    CALCULATE(
			        [Sum],
			        'Date'[Month (MM)] = _LatestMonth,
			        'Date'[Year (YYYY)] = _LatestYear
			    )
			VAR _Finish = [Sum (Latest Data Point)]
			VAR _Increase = UNICHAR( 8599 )
			VAR _Decrease = UNICHAR( 8600 )
			VAR _Delta = _Finish - _Start
			VAR _Arrow =
			    IF(
			        _Delta > 0,
			        _Increase & " Trending up",
			        _Decrease & " Trending down"
			    )
			RETURN
			    _Arrow
		isHidden
		displayFolder: Dynamic Titles
		lineageTag: cf8326ce-38a8-4c1f-91b8-fdd8f9b89b39

	measure 'KPI Trend Conditional Formatting' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			
			VAR _LatestDate =
			    CALCULATE(
			        MIN( 'Table'[Month] ),
			        VALUES( 'Date'[Year (YYYY)] ),
			        REMOVEFILTERS( )
			    )
			VAR _LatestMonth = MONTH( _LatestDate )
			VAR _LatestYear = YEAR( _LatestDate )
			VAR _Start =
			    CALCULATE(
			        [Sum],
			        'Date'[Month (MM)] = _LatestMonth,
			        'Date'[Year (YYYY)] = _LatestYear
			    )
			VAR _Finish = [Sum (Latest Data Point)]
			VAR _Increase = UNICHAR( 8599 )
			VAR _Decrease = UNICHAR( 8600 )
			VAR _Delta = _Finish - _Start
			VAR _Arrow =
			    IF( _Delta > 0, "#74afcc", "#c56161" )
			RETURN
			    _Arrow
		isHidden
		displayFolder: Control Colours
		lineageTag: e17710f3-dd05-4d60-ab0d-2faa2d3f6a19

	measure 'Sum (All Except Latest Point)' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			
			VAR _LatestDate =
			    CALCULATE(
			        MAX( 'Table'[Month] ),
			        REMOVEFILTERS( )
			    )
			VAR _LatestMonth = MONTH( _LatestDate )
			VAR _LatestYear = YEAR( _LatestDate )
			RETURN
			    CALCULATE(
			        [Sum],
			        'Date'[Month (MM)] <> _LatestMonth,
			        'Date'[Year (YYYY)] = _LatestYear
			    )
		isHidden
		displayFolder: KPI Trend
		lineageTag: c9e25d30-0f33-45d0-9b4c-9b0318ce13de

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'KPI Trend Comparison Subtitle' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			
			VAR _LatestDate =
			    CALCULATE(
			        MAX( 'Table'[Month] ),
			        VALUES( 'Date'[Year (YYYY)] ),
			        REMOVEFILTERS( )
			    )
			VAR _LatestMonth = MONTH( _LatestDate )
			VAR _LatestYear = YEAR( _LatestDate )
			VAR _Start =
			    CALCULATE(
			        [Sum (PY)],
			        'Date'[Month (MM)] = _LatestMonth,
			        'Date'[Year (YYYY)] = _LatestYear
			    )
			VAR _Finish = [Sum (Latest Data Point)]
			VAR _Increase = UNICHAR( 9650 )
			VAR _Decrease = UNICHAR( 9660 )
			VAR _Delta = _Finish - _Start
			VAR _Arrow =
			    IF(
			        _Delta > 0,
			        _Increase & " Higher than last year",
			        _Decrease & " Lower than last year"
			    )
			RETURN
			    _Arrow
		isHidden
		displayFolder: Dynamic Titles
		lineageTag: 05fa42ff-6662-4b17-a9ac-7ebb19000a65

	measure 'KPI Trend Comparison Conditional Formatting' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			
			VAR _LatestDate =
			    CALCULATE(
			        MAX( 'Table'[Month] ),
			        VALUES( 'Date'[Year (YYYY)] ),
			        REMOVEFILTERS( )
			    )
			VAR _LatestMonth = MONTH( _LatestDate )
			VAR _LatestYear = YEAR( _LatestDate )
			VAR _Start =
			    CALCULATE(
			        [Sum (PY)],
			        'Date'[Month (MM)] = _LatestMonth,
			        'Date'[Year (YYYY)] = _LatestYear
			    )
			VAR _Finish = [Sum (Latest Data Point)]
			VAR _Increase = UNICHAR( 9650 )
			VAR _Decrease = UNICHAR( 9660 )
			VAR _Delta = _Finish - _Start
			VAR _Arrow =
			    IF( _Delta > 0, "#74afcc", "#c56161" )
			RETURN
			    _Arrow
		isHidden
		displayFolder: Control Colours
		lineageTag: 572d9a0b-6fba-4154-b6b0-a073e99ec6eb

	measure 'KPI Sparkline Trend Up/Down' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			
			VAR _LatestDate =
			    CALCULATE (
			        MIN ( 'Table'[Month] ),
			        VALUES ( 'Date'[Year (YYYY)] ),
			        REMOVEFILTERS ( )
			    )
			VAR _LatestMonth = MONTH ( _LatestDate )
			VAR _LatestYear = YEAR ( _LatestDate )
			VAR _Start =
			    CALCULATE (
			        [Sum],
			        'Date'[Month (MM)] = _LatestMonth,
			        'Date'[Year (YYYY)] = _LatestYear
			    )
			VAR _Finish = [Sum (Latest Data Point)]
			VAR _Increase = UNICHAR ( 8599 )
			VAR _Decrease = UNICHAR ( 8600 )
			VAR _Delta = _Finish - _Start
			VAR _Arrow =
			    IF ( _Delta > 0, _Increase, _Decrease )
			RETURN
			    _Arrow
		isHidden
		displayFolder: Dynamic Titles
		lineageTag: 5d85f1a7-96b2-4a9f-a873-143edcd54282

	measure 'Gauge %' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _Goblins =
			    CALCULATE(
			        [Sum],
			        'Table'[Boolean Dimension] = "Approved"
			    )
			VAR _Perc = DIVIDE( _Goblins, [Sum] )
			RETURN
			    _Perc
		formatString: 0%;-0%;0%
		isHidden
		displayFolder: KPI Gauge
		lineageTag: c70eae56-3b9c-4b78-8306-110a1a9c49e2

	measure 'Issues or No Issues' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			VAR _Count = [Count]
			VAR _Symbol =
			    SWITCH(
			        TRUE( ),
			        _Count > 0, UNICHAR( 10008 ),
			        _Count = 0, UNICHAR( 10004 ),
			        BLANK( )
			    )
			RETURN
			    _Symbol
		isHidden
		displayFolder: Boolean Conditional Text
		lineageTag: 0075047b-501d-420f-91c0-6c4974a9ff2f

	measure '# Issues (Text)' =
			
			--Disclaimer: DAX in these templates doesn't follow best practices
			--            Don't use this DAX as-is; the templates are intended to be illustrative.
			
			REPT( UNICHAR( 10008 ), [Count] )
		isHidden
		displayFolder: Repeated Text
		lineageTag: b8c93b14-6f6e-44f4-92a4-208bca84475b

	column Value
		isHidden
		formatString: 0
		lineageTag: 05cd4f72-d741-444a-8849-796154a583d9
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition '2. Report-Specific Objects' = calculated
		mode: import
		source =
				
				{ 1 }

	annotation PBI_Id = 21661cfde1db4d40be113778b97a84f2

