table '2. Report-Specific Objects'
	isHidden
	lineageTag: bc077534-c5b0-40dd-9fb4-4bad6abc2bd2

	measure '1 - Percentage' = ```
			1 - [Percentage] 
			```
		isHidden
		displayFolder: For Stacked Percentages
		lineageTag: a797f413-2545-4e12-a017-c9decafc3fa4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zero = 0
		formatString: """ """
		isHidden
		displayFolder: Misc
		lineageTag: 9c5e001d-acf5-4a94-8c79-b36b22eddff2

		annotation PBI_FormatHint = {"isCustom":true}

	measure '90% of Sum' = 0.9 * [Sum]
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 3dfd2c42-1784-48db-b00d-f2279171b90d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Transparent = "#00000000"
		isHidden
		displayFolder: Control Colours
		lineageTag: 7af08448-2e99-4e55-a505-8e431865c8dd

	measure One = 1
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: Misc
		lineageTag: ac584242-db7d-4988-837c-5bd76985c46d

	measure '5% of Sum' = 0.05 * [Sum]
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 7bf36b78-b7d5-408b-860f-e141b73f3749

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '110% of Highest Sum' = ```
			
			1.1 
			* 
			CALCULATE(
			    [Sum],
			    TOPN(
			        1,
			        VALUES( 'Table'[Dimension] ),
			        [Sum]
			    )
			)
			```
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 5b18d1b8-9148-45f3-8893-a6f86d294363

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min One' = -1
		formatString: 0
		isHidden
		displayFolder: Misc
		lineageTag: ebff2474-2af1-4c1e-b138-c5f3c295c261

	measure '120% of Highest Sum' = ```
			
			1.2 
			* 
			CALCULATE(
			    [Sum],
			    TOPN(
			        1,
			        VALUES( 'Table'[Dimension] ),
			        [Sum]
			    )
			)
			```
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 372933e1-0e0e-457e-8349-6aaaaa5cb5d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum (2022; Inverse)' = - [Sum (PY)]
		formatString: #,##0; #,##0; #,##0
		isHidden
		displayFolder: For Format Strings
		lineageTag: 2ad4db16-6991-4157-8219-d80f6deb39ed

		annotation PBI_FormatHint = {"isCustom":true}

	measure 2022 = [Sum (2022; Inverse)]
		formatString: #,##0; #,##0; #,##0
		isHidden
		displayFolder: For Legends
		lineageTag: bec9c999-6fec-47de-8f1f-6e2ae0cd4437

		annotation PBI_FormatHint = {"isCustom":true}

	measure 2023 = [Sum (CY)]
		formatString: 0
		isHidden
		displayFolder: For Legends
		lineageTag: 8bcf8528-5a56-46a4-8577-7c5cfa488766

	measure 'Year Colour' = IF ( SELECTEDVALUE ( 'Table'[Year] ) = "  2022", "#ece6da", "#737068" )
		isHidden
		displayFolder: Control Colours
		lineageTag: 7a633807-acfb-4667-bf5f-0f51cfe82c98

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bar Chart & Candlestick - Change (Lower)' = ```
			
			IF ( 
			    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = "CHANGE",
			    MIN ( [Sum (PY)], [Sum (CY)] )
			)
			```
		isHidden
		displayFolder: For Bar Chart & Candlestick
		lineageTag: 42be94b5-2cf7-403f-b817-e793d939313a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bar Chart & Candlestick - Change (Higher)' = ```
			
			IF ( 
			    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = "CHANGE",
			    MAX ( [Sum (PY)], [Sum (CY)] )
			)
			```
		isHidden
		displayFolder: For Bar Chart & Candlestick
		lineageTag: 06a8e96e-b86e-4795-ae87-d11205f3f7ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bar Chart & Candlestick - Bar Color' = ```
			
			VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )
			RETURN
			IF ( 
			    _Attribute = "CHANGE",
			    "#00000000",
			    IF (
			        _Attribute = "2023", "#737068",
			        "#ece6da"
			    )
			)
			```
		isHidden
		displayFolder: For Bar Chart & Candlestick
		lineageTag: 2ac1fede-d563-4021-b19f-cb3ad7697b75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '120% of Highest Sum by Year' = ```
			
			1.2 
			* 
			CALCULATE(
			    [Sum],
			    TOPN(
			        1,
			        VALUES( 'Table'[Year] ),
			        [Sum]
			    )
			)
			```
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 72ea17f8-178e-48f7-a73d-2a0479fdd182

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bar Chart & Candlestick - Label Color' = ```
			
			VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )
			RETURN
			IF ( 
			    _Attribute = "CHANGE",
			    IF ( [Sum (Δ% PY - CY)] > 0, "#1f84bb", "#ec8b69" ), "#00000000" )
			```
		isHidden
		displayFolder: For Bar Chart & Candlestick
		lineageTag: 0442ff64-b4ae-4dd0-bab9-992d9e1ec8f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '120% of Highest Delta' = ```
			
			1.2 
			* 
			CALCULATE(
			    MAX( [Sum (PY)], [Sum (CY)] ),
			    TOPN(
			        1,
			        VALUES( 'Table'[Dimension] ),
			        MAX( [Sum (PY)], [Sum (CY)] )
			    )
			)
			```
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: e64df63d-9b51-4dea-b0c7-7cfd61781d41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min 2' = -2
		isHidden
		displayFolder: Duplicated Measures for Formatting
		lineageTag: 8a4b18d3-f2cd-440b-a115-9c6339b8ae7a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Zero #3' = 0
		isHidden
		displayFolder: Duplicated Measures for Formatting
		lineageTag: a4149ffb-966e-4875-a3a3-d540e6ece0e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Goblins = IF ( SELECTEDVALUE( 'Table'[Dimension] ) = "Goblins", 0.75 )
		formatString: 0%;-0%;0%
		displayFolder: For Progress Bar III
		lineageTag: 159adc75-7072-42b0-93ca-599cd80e5992

	measure 'Y-Axis (Progress III)' = ```
			
			VAR _Dimension = SELECTEDVALUE ( 'Table'[Dimension] ) 
			RETURN
			SWITCH(
			    _Dimension,
			    "Halflings", 0.95, 
			    "Goblins", 0.70,
			    "Orcs", 0.45,
			    "Elves", 0.20
			    ,0
			)
			```
		formatString: 0%;-0%;0%
		displayFolder: For Progress Bar III
		lineageTag: 3ae4415e-2da2-4c0a-9850-4dc0e09a9821

	measure Yellow = 0.25
		formatString: 0%;-0%;0%
		displayFolder: For Progress Bar III
		lineageTag: 7b2ecbaf-aa8b-439d-aeb4-dd5a256af54d

	measure Orcs = IF ( SELECTEDVALUE( 'Table'[Dimension] ) = "Goblins", 0.5 )
		formatString: 0%;-0%;0%
		displayFolder: For Progress Bar III
		lineageTag: c3bfd392-d6d1-4ed7-ba57-e90ec17dc9e8

	measure Halflings = IF ( SELECTEDVALUE( 'Table'[Dimension] ) = "Halflings", 1 )
		formatString: 0%;-0%;0%
		displayFolder: For Progress Bar III
		lineageTag: 69d09b41-5a01-404b-b885-00bcb54f8111

	measure 'Sum CY (Bar)' = [Sum (CY)]
		lineageTag: afbf49c9-e1ef-403d-b6de-ab8706de94a2

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum PY (Bar)' = [Sum (PY)]
		lineageTag: 3a2ec604-108a-4706-abc9-8dd5db5b98b3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum Delta (Bar)' = [Sum (ΔPY - CY)]
		lineageTag: de23fae5-03fa-430c-b188-b18aca5161a7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		isHidden
		formatString: 0
		lineageTag: 05cd4f72-d741-444a-8849-796154a583d9
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition '2. Report-Specific Objects' = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 21661cfde1db4d40be113778b97a84f2

