table Table
	lineageTag: 74c7dcbc-f534-4da1-9c59-174298c17e81

	column Dimension
		dataType: string
		lineageTag: b6428db5-956a-46cf-8e0d-f78eb01375b5
		summarizeBy: none
		sourceColumn: Dimension

		annotation SummarizationSetBy = Automatic

	column Quantitative
		dataType: int64
		formatString: 0
		lineageTag: ea479855-4c8e-45af-927c-60b87abbeb86
		summarizeBy: sum
		sourceColumn: Quantitative

		annotation SummarizationSetBy = Automatic

	column Sub-Dimension
		dataType: string
		lineageTag: 9f44d7b1-03be-4dc8-ad1c-32b4503fb996
		summarizeBy: none
		sourceColumn: Sub-Dimension

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: string
		lineageTag: f94a7412-424a-4c12-9e19-6a928be50131
		summarizeBy: none
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition Table = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wcs9PysnMK1bSUQrKTy9NBTEUFIwMjIyADCOlWB1kFeGZVYlFKXAlxkCGKZoSt8z0jJLUIhRjzNHU+ObnZaMYYgxW4F+UjN0ZFsjSWNxgaIisAJsLDFFswLAf4kDXnLJU7A4wNEVRgM0JRigqsLrBEkUJhiOglngk5qQBwykdu0uMMdRgcYwJhiKs7sFQheEkoKdiAQ==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Dimension = _t, #"Sub-Dimension" = _t, Year = _t, Quantitative = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Quantitative", Int64.Type}, {"Year", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

