table '1. Measures'
	lineageTag: 4bd4c7d3-ed8c-4fc9-802b-4eb3b0893f5d

	measure Percentage = ```
			
			VAR _Total = CALCULATE( SUM ( 'Table'[Quantitative] ), REMOVEFILTERS ( ) )
			RETURN
			DIVIDE ( 
			    SUM ( 'Table'[Quantitative] ), 
			    _Total
			) + 0.15
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ccbbf42b-88e3-4b49-8192-f592b6d02dc4

	measure Average = AVERAGE ( 'Table'[Quantitative] )
		formatString: "  #,##0.0"
		lineageTag: 71445de7-2cd6-43b8-81cb-8b9dd1159740

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Average (2023)' =
			
			// This would normally be just the sum; where Sum (2022) would be using time intelligence or a similar method to calculate PY
			CALCULATE(
			    [Average],
			    'Table'[Year] = "  2023"
			)
		formatString: 0
		lineageTag: 202a6bc8-71c3-41cc-9349-cde551b031a0

	measure 'Average (2022)' =
			
			// This would normally be calculated using time intelligence or a similar method to calculate PY
			CALCULATE(
			    [Average],
			    'Table'[Year] = "  2022"
			)
		formatString: 0
		lineageTag: 6fe52e9a-2944-457b-97e7-ee4aadcdc2cc

	measure 'Average (Δ ''22 - ''23)' =
			
			VAR _CY = [Average (2023)]
			VAR _PY = [Average (2022)]
			VAR _Delta = _CY - _PY
			RETURN
			_Delta
		formatString: 0
		lineageTag: 4cb18752-6c6d-444e-b2dd-dff2e86ce817

	measure 'Average (Δ% ''22 - ''23)' =
			
			DIVIDE (
			    [Average (Δ '22 - '23)],
			    [Average (2022)]
			)
		formatString: +#,##0.0%;-#,##0.0%;#,##0.0%
		lineageTag: 546753a4-f8e4-45be-92c8-3a0ccdc60f66

		annotation PBI_FormatHint = {"isCustom":true}

	measure SD = ```
			
			    STDEV.S ( 'Table'[Quantitative] )
			```
		lineageTag: 489d3676-df3a-464a-b8ae-a7f906557fd1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sum = SUM ( 'Table'[Quantitative] )
		lineageTag: 13f3c9e7-2e88-4875-bb0c-dc7c0ce2da62

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		isHidden
		formatString: 0
		lineageTag: 18e219e8-e8e5-4a4e-8c86-825ff8a663c7
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition '1. Measures' = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 724d8a875a79418db6f9113a2cf5d8eb

