table '2. Report-Specific Objects'
	isHidden
	lineageTag: bc077534-c5b0-40dd-9fb4-4bad6abc2bd2

	measure '1 - Percentage' = ```
			1 - [Percentage] 
			```
		isHidden
		displayFolder: For Stacked Percentages
		lineageTag: a797f413-2545-4e12-a017-c9decafc3fa4

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Zero = 0
		formatString: 0
		isHidden
		displayFolder: Misc
		lineageTag: 9c5e001d-acf5-4a94-8c79-b36b22eddff2

	measure '90% of Sum' = 0.9 * [Average]
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 3dfd2c42-1784-48db-b00d-f2279171b90d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Transparent = "#00000000"
		isHidden
		displayFolder: Control Colours
		lineageTag: 7af08448-2e99-4e55-a505-8e431865c8dd

	measure One = 17
		formatString: 0.0%;-0.0%;0.0%
		isHidden
		displayFolder: Misc
		lineageTag: ac584242-db7d-4988-837c-5bd76985c46d

	measure '5% of Sum' = 0.05 * [Average]
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 7bf36b78-b7d5-408b-860f-e141b73f3749

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '110% of Highest Sum' = ```
			
			1.1 
			* 
			CALCULATE(
			    [Average],
			    TOPN(
			        1,
			        VALUES( 'Date'[Month (MMM)] ),
			        [Average]
			    )
			)
			```
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 5b18d1b8-9148-45f3-8893-a6f86d294363

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min One' = -1
		formatString: 0
		isHidden
		displayFolder: Misc
		lineageTag: ebff2474-2af1-4c1e-b138-c5f3c295c261

	measure '120% of Highest Sum' = ```
			
			1.2 
			* 
			CALCULATE(
			    [Average],
			    TOPN(
			        1,
			        VALUES( 'Date'[Month (MMM)] ),
			        [Average]
			    )
			)
			```
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 372933e1-0e0e-457e-8349-6aaaaa5cb5d9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum (2022; Inverse)' = - [Average (2022)]
		formatString: #,##0; #,##0; #,##0
		isHidden
		displayFolder: For Format Strings
		lineageTag: 2ad4db16-6991-4157-8219-d80f6deb39ed

		annotation PBI_FormatHint = {"isCustom":true}

	measure 2022 = [Sum (2022; Inverse)]
		formatString: #,##0; #,##0; #,##0
		isHidden
		displayFolder: For Legends
		lineageTag: bec9c999-6fec-47de-8f1f-6e2ae0cd4437

		annotation PBI_FormatHint = {"isCustom":true}

	measure 2023 = [Average (2023)]
		formatString: 0
		isHidden
		displayFolder: For Legends
		lineageTag: 8bcf8528-5a56-46a4-8577-7c5cfa488766

	measure 'Year Colour' = IF ( SELECTEDVALUE ( 'Table'[Year] ) = "  2022", "#ece6da", "#737068" )
		isHidden
		displayFolder: Control Colours
		lineageTag: 7a633807-acfb-4667-bf5f-0f51cfe82c98

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bar Chart & Candlestick - Change (Lower)' = ```
			
			IF ( 
			    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = "CHANGE",
			    MIN ( [Average (2022)], [Average (2023)] )
			)
			```
		isHidden
		displayFolder: For Bar Chart & Candlestick
		lineageTag: 42be94b5-2cf7-403f-b817-e793d939313a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bar Chart & Candlestick - Change (Higher)' = ```
			
			IF ( 
			    SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] ) = "CHANGE",
			    MAX ( [Average (2022)], [Average (2023)] )
			)
			```
		isHidden
		displayFolder: For Bar Chart & Candlestick
		lineageTag: 06a8e96e-b86e-4795-ae87-d11205f3f7ee

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bar Chart & Candlestick - Bar Color' = ```
			
			VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )
			RETURN
			IF ( 
			    _Attribute = "CHANGE",
			    "#00000000",
			    IF (
			        _Attribute = "2023", "#737068",
			        "#ece6da"
			    )
			)
			```
		isHidden
		displayFolder: For Bar Chart & Candlestick
		lineageTag: 2ac1fede-d563-4021-b19f-cb3ad7697b75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '120% of Highest Sum by Year' = ```
			
			1.2 
			* 
			CALCULATE(
			    [Average],
			    TOPN(
			        1,
			        VALUES( 'Table'[Year] ),
			        [Average]
			    )
			)
			```
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: 72ea17f8-178e-48f7-a73d-2a0479fdd182

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Bar Chart & Candlestick - Label Color' = ```
			
			VAR _Attribute = SELECTEDVALUE ( '3. Report-Specific Disconnected Table'[Attribute] )
			RETURN
			IF ( 
			    _Attribute = "CHANGE",
			    IF ( [Average (Δ% '22 - '23)] > 0, "#1f84bb", "#ec8b69" ), "#00000000" )
			```
		isHidden
		displayFolder: For Bar Chart & Candlestick
		lineageTag: 0442ff64-b4ae-4dd0-bab9-992d9e1ec8f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure '120% of Highest Delta' = ```
			
			1.2 
			* 
			CALCULATE(
			    MAX( [Average (2022)], [Average (2023)] ),
			    TOPN(
			        1,
			        VALUES( 'Date'[Month (MMM)] ),
			        MAX( [Average (2022)], [Average (2023)] )
			    )
			)
			```
		isHidden
		displayFolder: Control Axis Ranges
		lineageTag: e64df63d-9b51-4dea-b0c7-7cfd61781d41

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min 2' = -2
		isHidden
		displayFolder: Duplicated Measures for Formatting
		lineageTag: 8a4b18d3-f2cd-440b-a115-9c6339b8ae7a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Zero #3' = 0
		isHidden
		displayFolder: Duplicated Measures for Formatting
		lineageTag: a4149ffb-966e-4875-a3a3-d540e6ece0e0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sum (Latest Data Point)' =
			
			CALCULATE(
			    [Average],
			    'Date'[IsLatestMonth],
			    KEEPFILTERS( VALUES ( 'Date'[Month (MMM)] ) )
			)
		formatString: 0
		isHidden
		displayFolder: Label Latest Data Point
		lineageTag: 55d3fdf6-89df-4b96-9fc9-65ba8a5f157d

	measure 'Threshold (Higher)' = ```
			
			VAR _Months = FILTER( VALUES( 'Date'[Month (MMM)] ), COUNTROWS( 'Table' ) > 0 )
			VAR _SelectedMonth = SELECTEDVALUE( 'Date'[Month (MMM)] ) 
			VAR _Threshold = [Threshold]
			RETURN
			IF ( [Average] >= _Threshold,
			    IF ( _SelectedMonth IN _Months, _Threshold, BLANK() ) 
			) 
			```
		isHidden
		displayFolder: Thresholds and Horizontal Areas
		lineageTag: f00dfc04-d6b9-44ff-b743-45405d58c22e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Threshold = 4.8
		isHidden
		displayFolder: Thresholds and Horizontal Areas
		lineageTag: 70912a2f-7fdc-40f8-aa4c-bb8ceb75e567

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Threshold (Lower)' = ```
			
			VAR _Months = FILTER( VALUES( 'Date'[Month (MMM)] ), COUNTROWS( 'Table' ) > 0 )
			VAR _SelectedMonth = SELECTEDVALUE( 'Date'[Month (MMM)] ) 
			VAR _Threshold = [Threshold]
			RETURN
			IF ( [Average] <= _Threshold,
			    IF ( _SelectedMonth IN _Months, _Threshold, BLANK() ) 
			) 
			```
		isHidden
		displayFolder: Thresholds and Horizontal Areas
		lineageTag: f834f7ac-25ff-4ab5-a228-3cb8d5ad14d7

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Highlight = ```
			
			IF ( 
			    SELECTEDVALUE ( 'Date'[IsLatestMonth] ) = TRUE(), 
			    1, 
			    BLANK()
			)
			```
		isHidden
		displayFolder: Highlight Vertical Area
		lineageTag: 2131f417-e0b0-4648-8866-11eee637812d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Highlighted Month' = ```
			
			IF ( 
			    COUNTROWS( VALUES ( 'Date'[Month (MMM)] ) ) = 12,
			    "#005486",
			    "#ada79b"
			)
			```
		isHidden
		displayFolder: Highlight Vertical Area
		lineageTag: 8135898e-8d0a-4140-8880-d79a4718f271

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Month = ```
			MAX( 'Date'[Month (#)] ) 
			```
		isHidden
		displayFolder: Highlight Vertical Area
		lineageTag: f75cdff8-6112-4226-8525-172496dd5503

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Threshold (Top)' = 7
		isHidden
		displayFolder: Thresholds and Horizontal Areas
		lineageTag: 3bd79048-e547-450e-9c11-d0d0a4995ffe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Blank = BLANK()
		isHidden
		displayFolder: Misc
		lineageTag: bc1a9073-c74e-4bef-a16a-79a7e75044f5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average - 1SD' = ```
			[Average] - [SD] 
			```
		isHidden
		displayFolder: Error Bands
		lineageTag: a376f3b9-65d9-44c9-9af1-f75308bce45a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average + 1SD' = ```
			[Average] + [SD] 
			```
		isHidden
		displayFolder: Error Bands
		lineageTag: 22523ff4-a7f5-4fbf-84de-218f21e79cfd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dumbbell Candle Upper (Red)' =
			
			VAR _CY = [Average (2023)]
			VAR _PY = [Average (2022)]
			RETURN
			IF ( _CY < _PY, _PY )
		isHidden
		displayFolder: For Dumbbell Charts
		lineageTag: d636fe70-992e-4e3b-a007-3613a2b538a8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dumbbell Candle Upper (Green)' =
			
			VAR _CY = [Average (2023)]
			VAR _PY = [Average (2022)]
			RETURN
			IF ( _CY > _PY, _CY )
		isHidden
		displayFolder: For Dumbbell Charts
		lineageTag: ddabfcbe-403f-4e32-bb5c-9c775387f4fe

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dumbbell Candle Lower (Red)' =
			
			VAR _CY = [Average (2023)]
			VAR _PY = [Average (2022)]
			RETURN
			IF ( _CY < _PY, _CY )
		isHidden
		displayFolder: For Dumbbell Charts
		lineageTag: 38f51b3a-e517-4ced-8582-2c1941fc8caf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Dumbbell Candle Lower (Green)' =
			
			VAR _CY = [Average (2023)]
			VAR _PY = [Average (2022)]
			RETURN
			IF ( _CY > _PY, _PY )
		isHidden
		displayFolder: For Dumbbell Charts
		lineageTag: efacd5f7-169e-4e7d-b4fd-746f35c92480

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Value
		isHidden
		formatString: 0
		lineageTag: 05cd4f72-d741-444a-8849-796154a583d9
		summarizeBy: sum
		isNameInferred
		sourceColumn: [Value]

		annotation SummarizationSetBy = Automatic

	partition '2. Report-Specific Objects' = calculated
		mode: import
		source = {1}

	annotation PBI_Id = 21661cfde1db4d40be113778b97a84f2

