table _measures
	lineageTag: 9452c871-433c-4553-9ec0-1fd4c4b98b20

	measure 'Active Stores' = CALCULATE( DISTINCTCOUNT( DIM_Store[store_code] ), DIM_Store[store_status] = "Open" )
		formatString: #,0
		displayFolder: Geography
		lineageTag: faf2c38b-5fbf-4fd9-8e8b-d709cf5c6cc4

	measure 'Gross Revenue' =
			
			SUMX( FCT_Sales, FCT_Sales[quantity] * FCT_Sales[unit_price] )
		formatString: #,0
		displayFolder: KPI - Sales
		lineageTag: 3864f6ec-b4b3-490c-9438-ea79216f1524

	measure 'Avg Order Value' =
			
			DIVIDE( [Net Revenue], [Orders] )
		formatString: #,0
		displayFolder: KPI - Sales
		lineageTag: 2b253de4-d5c1-4ff6-a346-402f12dfe2cd

	measure 'Line Items' =
			
			VAR Lines =
			    SUMMARIZE( FCT_Sales, FCT_Sales[order_number], FCT_Sales[line_number] )
			RETURN
			    COUNTROWS( Lines )
		formatString: #,0
		displayFolder: KPI - Sales
		lineageTag: a4844a3d-9c34-4559-baff-02afad5837e3

	measure 'Avg Line Items' =
			
			DIVIDE( [Line Items], [Orders] )
		formatString: #,0.0
		displayFolder: KPI - Sales
		lineageTag: e005c246-045e-4973-b668-58256212399e

	measure 'Orders SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Orders], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: 24115dae-b5ea-42af-900c-381d7ea38ab4

	measure 'Orders Delta' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Orders], 'dim_date'[date], "DELTA" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: 20d3e1e7-6a17-4882-bf35-b7c554d99a6f

	measure 'Orders Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Orders], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Time Intelligence
		lineageTag: f8005450-11bc-4b89-849a-293596b0523b

	measure 'Avg Order Value SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Avg Order Value], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: 9583fcc9-d6d6-46ea-9943-f570fcacb476

	measure 'Avg Order Value Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Avg Order Value], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Time Intelligence
		lineageTag: d90eaa1e-6a7f-47ea-b01f-6578a8d22653

	measure Customers =
			
			DISTINCTCOUNT( DIM_Customer[customer_key] )
		formatString: #,0
		displayFolder: Customer
		lineageTag: 31d810bc-e553-408e-81a7-700cf58a780e

	measure 'Average Age' =
			
			AVERAGE( DIM_Customer[age] )
		formatString: #,0.0
		displayFolder: Customer
		lineageTag: 8fa88e1c-5e1a-4543-b5fd-eca08708718f

	measure 'Revenue per Customer' = DIVIDE( [Net Revenue], DISTINCTCOUNT( FCT_Sales[customer_key] ) )
		formatString: #,0
		displayFolder: Customer
		lineageTag: 47983de3-d642-49c7-a2ef-fca38e95da06

	measure 'Repeat Rate' =
			
			VAR T =
			    SUMMARIZE(
			        FCT_Sales,
			        FCT_Sales[customer_key],
			        "Orders", DISTINCTCOUNT( FCT_Sales[order_number] )
			    )
			RETURN
			    DIVIDE(
			        COUNTROWS( FILTER( T, [Orders] >= 2 ) ),
			        COUNTROWS( T )
			    )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Customer
		lineageTag: 1bcdbf15-9f52-4285-98c4-f7364015a2bb

	measure 'Unique Products' =
			
			DISTINCTCOUNT( DIM_Product[product_key] )
		formatString: #,0
		displayFolder: Product
		lineageTag: ae73af14-1585-4b5d-a5ea-71cd33bc1ac0

	measure 'Active Brands' =
			
			DISTINCTCOUNT( DIM_Product[brand] )
		formatString: #,0
		displayFolder: Product
		lineageTag: f5ee2e74-3a83-4f58-9172-a2f8f3775f5a

	measure 'Avg Unit Price' =
			
			DIVIDE( [Net Revenue], [Units Sold] )
		formatString: #,0.00
		displayFolder: Product
		lineageTag: c26fbbd4-6893-4e80-90b8-03e7c9b4e790

	measure Stores =
			
			DISTINCTCOUNT( DIM_Store[store_code] )
		formatString: #,0
		displayFolder: Geography
		lineageTag: a88ee692-370b-4fe3-86ba-e05f8b44d831

	measure 'Closed Stores' = CALCULATE( DISTINCTCOUNT( DIM_Store[store_code] ), DIM_Store[store_status] = "Closed" )
		formatString: #,0
		displayFolder: Geography
		lineageTag: e37ee5c3-656b-48e5-9e7f-1f2d1a30f8da

	measure 'Avg Sq Meters' =
			
			AVERAGE( DIM_Store[square_meters] )
		formatString: #,0.0
		displayFolder: Geography
		lineageTag: d3bd467f-a518-48c0-9313-cc80b55feca4

	measure 'Revenue per Store' =
			DIVIDE(
			    [Physical Revenue],
			    CALCULATE( DISTINCTCOUNT( DIM_Store[store_code] ), DIM_Store[channel] = "Physical", DIM_Store[store_status] = "Open" )
			)
		formatString: #,0
		displayFolder: Geography
		lineageTag: 49b67028-fefb-433e-913b-c5d8af71372f

	measure 'Revenue per Sq Meter' =
			DIVIDE(
			    [Physical Revenue],
			    CALCULATE( SUM( DIM_Store[square_meters] ), DIM_Store[channel] = "Physical", DIM_Store[store_status] = "Open" )
			)
		formatString: #,0.00
		displayFolder: Geography
		lineageTag: 1dcbc75e-a72e-4d40-b8d0-52f663438d80

	measure 'Sales Amount USD' =
			
			SUMX(
			    FCT_Sales,
			    FCT_Sales[quantity] * FCT_Sales[net_price] * FCT_Sales[exchange_rate]
			)
		formatString: #,0
		isHidden
		displayFolder: Currency
		lineageTag: 849c3fc0-539d-4ff3-a180-8f36a8fe79be

		changedProperty = IsHidden

	measure 'Net Profit SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Net Profit], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: 95c1be3d-f3ea-4213-adf1-9dc337209127

	measure 'Margin % SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Margin %], 'dim_date'[date], "SPLY" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Time Intelligence
		lineageTag: 1c5116c2-2c5f-41ca-a32a-82eb6cd3eb5d

	measure 'Margin Delta pp' =
			VAR _TotalDates  = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = _TotalDates
			VAR MarginNow    = [Margin %]
			VAR MarginPrior  = udf.adaptfy.timeintellgence( [Margin %], 'dim_date'[date], "SPLY" )
			RETURN
			    IF(
			        _AllSelected,
			        0,
			        IF(
			            NOT ISBLANK( MarginNow ) && NOT ISBLANK( MarginPrior ),
			            ( MarginNow - MarginPrior ) * 100
			        )
			    )
		formatString: 0.00 "pp";-0.00 "pp";0.00 "pp"
		displayFolder: KPI - Time Intelligence
		lineageTag: 7fb52cfa-0ecd-4600-945e-faff4215cbb4

		annotation PBI_FormatHint = {"isCustom":true}

	measure 'Line Items SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Line Items], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: e7cdc5d2-74f9-4079-b546-c3fb2aedac8e

	measure 'Avg Line Items SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Avg Line Items], 'dim_date'[date], "SPLY" ) )
		formatString: #,0.0
		displayFolder: KPI - Time Intelligence
		lineageTag: 09fd9b86-e1da-4823-907e-e427f30e07d3

	measure 'Avg Line Items Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Avg Line Items], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Time Intelligence
		lineageTag: 14a417fe-1057-47b1-9941-13424385984d

	measure 'Sales Amount Color' = udf.adaptfy.color.ragHex( [Revenue Delta], "NORMAL" )
		displayFolder: Formatting - Examples
		lineageTag: c43a03a2-5c24-4c71-9502-c6bf9a77b79b

	measure 'Units Sold SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Units Sold], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: 9bb90789-405e-4585-9ffd-e1055936111a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue Arrow' = udf.adaptfy.svg.ragArrow( [Revenue Delta], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 4a912ea5-a0c1-4caf-97bc-f08085bc7428
		dataCategory: ImageUrl

	measure 'Units Sold Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Units Sold], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Time Intelligence
		lineageTag: d248483a-b305-4c6e-989a-b1d434c3acbb

	measure Blank =
			
			" "
		displayFolder: Formatting - Examples
		lineageTag: 54d5aec7-a549-46dd-b9a4-daf45afbd8c4

	measure 'Net Profit Arrow' =
			
			udf.adaptfy.svg.ragArrow( [Net Profit Delta], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: e2668a49-2632-4c1e-b1f4-6f899d2d85bc
		dataCategory: ImageUrl

	measure 'Revenue Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Net Revenue], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Time Intelligence
		lineageTag: 43743009-aa61-4181-b0f9-1227edb29a43

	measure 'Revenue Delta' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Net Revenue], 'dim_date'[date], "DELTA" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: cb8db50e-9b3f-40a5-a7de-802a76ec2345

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Revenue SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Net Revenue], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: e379e66c-74cc-4dc9-bea7-2f0714ce63e8

	measure 'Units Sold Arrow' = udf.adaptfy.svg.ragArrow( [Units Sold Delta], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: efa11e5f-02c9-4e1c-a6db-9aa399e8d923
		dataCategory: ImageUrl

	measure 'Units Sold Delta' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Units Sold], 'dim_date'[date], "DELTA" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: 7b658a85-a6b2-49e4-a2fe-00eae3825ed9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Orders Arrow' = udf.adaptfy.svg.ragArrow( [Orders Delta], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 1e4c7192-6c15-4b21-ba80-1a4c5708a525
		dataCategory: ImageUrl

	measure 'Net Profit Delta' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Net Profit], 'dim_date'[date], "DELTA" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: 1134539e-70b5-44a3-8366-94677ea4270b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Net Profit Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Net Profit], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Time Intelligence
		lineageTag: ee7d96a7-2324-46e9-a518-b7da00bb34b3

	measure 'Margin Arrow' =
			
			udf.adaptfy.svg.ragArrow( [Margin Delta pp], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 5c71a756-5c41-496a-843e-93323170b430
		dataCategory: ImageUrl

	measure 'Discount %' = DIVIDE( [Gross Revenue] - [Net Revenue], [Gross Revenue] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Sales
		lineageTag: e9fea506-954b-481b-9cdf-9af265d76b0a

	measure 'Gross Revenue SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Gross Revenue], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: KPI - Sales
		lineageTag: 1954d173-4e0c-46e5-9a02-b2036aa0b042

	measure 'Gross Revenue Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Gross Revenue], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Sales
		lineageTag: bb90828c-060a-4f36-9f19-e457bef7a703

	measure 'Revenue % of Total' =
			DIVIDE(
			    [Net Revenue],
			    CALCULATE( [Net Revenue], ALL( DIM_Product[category] ), ALL( DIM_Store[country] ) )
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Sales
		lineageTag: 62a50780-9eb9-4e8b-8dcc-5be1c83e96b4

	measure 'Top Country' =
			CALCULATE(
			    SELECTEDVALUE( DIM_Store[country] ),
			    TOPN( 1, ALL( DIM_Store[country] ), [Net Revenue], DESC )
			)
		displayFolder: KPI - Sales
		lineageTag: daea6f30-ce54-4b0a-bbde-d9bdc1e9d87a

	measure 'Top Category' =
			CALCULATE(
			    SELECTEDVALUE( DIM_Product[category] ),
			    TOPN( 1, ALL( DIM_Product[category] ), [Net Revenue], DESC )
			)
		displayFolder: KPI - Sales
		lineageTag: 48e9161a-552c-412d-8ca4-392b4808f1ad

	measure 'Margin % Axis Min' =
			VAR VisibleMin    = MINX( VALUES( 'DIM_Date'[year_month_number] ), [Margin %] )
			VAR VisibleMax    = MAXX( VALUES( 'DIM_Date'[year_month_number] ), [Margin %] )
			VAR VisibleRange  = VisibleMax - VisibleMin
			VAR Padding       = MAX( VisibleRange * 0.5, 0.005 )  -- at least 0.5pp padding each side
			RETURN
			    FLOOR( ( VisibleMin - Padding ) * 100, 0.5 ) / 100
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Formatting - Examples
		lineageTag: 16a42d36-6622-455a-9708-1a621e589ce2

	measure 'Margin % Axis Max' =
			VAR VisibleMin    = MINX( VALUES( 'DIM_Date'[year_month_number] ), [Margin %] )
			VAR VisibleMax    = MAXX( VALUES( 'DIM_Date'[year_month_number] ), [Margin %] )
			VAR VisibleRange  = VisibleMax - VisibleMin
			VAR Padding       = MAX( VisibleRange * 0.5, 0.005 )  -- at least 0.5pp padding each side
			RETURN
			    CEILING( ( VisibleMax + Padding ) * 100, 0.5 ) / 100
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Formatting - Examples
		lineageTag: d406af72-94d6-4ad4-9c03-9d889e4a9701

	measure 'Revenue per Store SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Revenue per Store], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: Geography
		lineageTag: 8b654972-9758-430f-b792-d61512c2b46b

	measure 'Revenue per Store Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Revenue per Store], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Geography
		lineageTag: fd0c6268-a990-41ec-991e-750da150ec3d

	measure 'Revenue per Store Arrow' = udf.adaptfy.svg.ragArrow( [Revenue per Store Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: fd3d5ccb-f577-4f71-814f-8f43e53d01df
		dataCategory: ImageUrl

	measure 'Revenue per Sq Meter SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Revenue per Sq Meter], 'dim_date'[date], "SPLY" ) )
		formatString: #,0.00
		displayFolder: Geography
		lineageTag: 6eb5ca64-0938-4754-8b2b-39fe454f3465

	measure 'Revenue per Sq Meter Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Revenue per Sq Meter], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Geography
		lineageTag: 7d35872b-d61f-4e58-912a-72a4d7ab94fd

	measure 'Online vs Physical %' =
			DIVIDE(
			    CALCULATE( [Net Revenue], DIM_Store[channel] = "Online" ),
			    [Net Revenue]
			)
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Geography
		lineageTag: 5daa8fa7-51ba-4fab-8981-b36147227a3b

	measure 'Physical Revenue' = CALCULATE( [Net Revenue], DIM_Store[channel] = "Physical" )
		formatString: #,0
		displayFolder: Geography
		lineageTag: ab484a54-5cc3-4f90-9786-8f97c461c573

	measure 'Online Revenue' = CALCULATE( [Net Revenue], DIM_Store[channel] = "Online" )
		formatString: #,0
		displayFolder: Geography
		lineageTag: 1e6c25ea-db50-4e01-b3e9-1fd53d8a8f16

	measure 'Avg Store Size' =
			CALCULATE(
			    AVERAGE( DIM_Store[square_meters] ),
			    DIM_Store[store_status] = "Open",
			    DIM_Store[channel] = "Physical"
			)
		formatString: #,0.0
		displayFolder: Geography
		lineageTag: 8c34f16e-9c08-4bcc-b0d2-4480e6a65da1

	measure 'Store Closure Rate' = DIVIDE( [Closed Stores], [Stores] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Geography
		lineageTag: a35ecd9c-44bd-4a35-988a-665e902a6c4c

	measure 'Online Revenue SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Online Revenue], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: Geography
		lineageTag: 3325cc2b-5263-46b7-8bd8-2ec7cdbba525

	measure 'Online Revenue Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Online Revenue], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Geography
		lineageTag: f395aa59-a07b-43ca-9278-6f13d28ffdee

	measure 'Physical Revenue SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Physical Revenue], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: Geography
		lineageTag: ffd4cd32-f753-4760-8756-b45a2f66d5c4

	measure 'Physical Revenue Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Physical Revenue], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Geography
		lineageTag: 43d97d7e-9ef8-4e15-a341-c1966aada8f5

	measure 'Online Revenue Arrow' = udf.adaptfy.svg.ragArrow( [Online Revenue Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 974dca14-bcf7-4135-bff0-d454a9de6ab9
		dataCategory: ImageUrl

	measure 'Physical Revenue Arrow' = udf.adaptfy.svg.ragArrow( [Physical Revenue Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 627ed6bf-66cf-453a-8932-0fab34df3940
		dataCategory: ImageUrl

	measure 'Store Summary Banner' =
			VAR PhysicalOpen = CALCULATE( DISTINCTCOUNT( DIM_Store[store_code] ), DIM_Store[channel] = "Physical", DIM_Store[store_status] = "Open" )
			VAR OnlineOpen   = CALCULATE( DISTINCTCOUNT( DIM_Store[store_code] ), DIM_Store[channel] = "Online",   DIM_Store[store_status] = "Open" )
			RETURN
			    FORMAT( PhysicalOpen, "0" ) & " physical stores  ·  " &
			    FORMAT( OnlineOpen,   "0" ) & " online store"
		displayFolder: Formatting - Examples
		lineageTag: 836eb567-526d-4645-88e0-0e5f88d26583

	measure 'Online Share SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Online vs Physical %], 'dim_date'[date], "SPLY" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Geography
		lineageTag: dd34c386-2f72-4260-b7cc-e1725dcaead0

	measure 'Online Share Delta pp' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			VAR OnlinePctNow   = [Online vs Physical %]
			VAR OnlinePctPrior = udf.adaptfy.timeintellgence( [Online vs Physical %], 'dim_date'[date], "SPLY" )
			RETURN
			    IF(
			        _AllSelected,
			        0,
			        IF(
			            NOT ISBLANK( OnlinePctNow ) && NOT ISBLANK( OnlinePctPrior ),
			            ( OnlinePctNow - OnlinePctPrior ) * 100
			        )
			    )
		formatString: 0.00 "pp";-0.00 "pp";0.00 "pp"
		displayFolder: Geography
		lineageTag: 56e1b707-66e3-42e9-af71-0f72a050397a

	measure 'Online Share Arrow' = udf.adaptfy.svg.ragArrow( [Online Share Delta pp], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 65820d5c-441c-46cc-b1b1-876ff630913e
		dataCategory: ImageUrl

	measure 'Revenue per Sq Meter Arrow' = udf.adaptfy.svg.ragArrow( [Revenue per Sq Meter Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 3d604efc-7ee9-495e-911d-b316982b9ad9
		dataCategory: ImageUrl

	measure 'Revenue per Store Delta' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Revenue per Store], 'dim_date'[date], "DELTA" ) )
		formatString: #,0
		displayFolder: Geography
		lineageTag: 1b73b505-f87a-4fd4-b6ff-663c85353adc

	measure 'Revenue per Sq Meter Delta' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Revenue per Sq Meter], 'dim_date'[date], "DELTA" ) )
		formatString: #,0.00
		displayFolder: Geography
		lineageTag: f3ea7150-69da-4207-85dd-0e73fb4db17c

	measure 'Avg Unit Price SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Avg Unit Price], 'dim_date'[date], "SPLY" ) )
		formatString: #,0.00
		displayFolder: Product
		lineageTag: be00ad1d-1306-4d43-8ad8-2da71ad62295

	measure 'Avg Unit Price Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Avg Unit Price], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Product
		lineageTag: 90ad7dc9-7232-46e0-8743-263feac69b64

	measure 'Avg Unit Price Arrow' = udf.adaptfy.svg.ragArrow( [Avg Unit Price Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 883f2e3b-7300-40a7-aa6d-2e8b09aedd51
		dataCategory: ImageUrl

	measure 'Discount % SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Discount %], 'dim_date'[date], "SPLY" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Product
		lineageTag: a8508f7b-92fe-4fe0-bd5f-6d74305ac2db

	measure 'Discount Delta pp' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			VAR DiscountNow    = [Discount %]
			VAR DiscountPrior  = udf.adaptfy.timeintellgence( [Discount %], 'dim_date'[date], "SPLY" )
			RETURN
			    IF(
			        _AllSelected,
			        0,
			        IF(
			            NOT ISBLANK( DiscountNow ) && NOT ISBLANK( DiscountPrior ),
			            ( DiscountNow - DiscountPrior ) * 100
			        )
			    )
		formatString: 0.00 "pp";-0.00 "pp";0.00 "pp"
		displayFolder: Product
		lineageTag: 0921ea12-7cda-4aa1-ac67-bad752431a92

	measure 'Revenue per Product' = DIVIDE( [Net Revenue], [Unique Products] )
		formatString: #,0
		displayFolder: Product
		lineageTag: 17e2cf0b-34ee-4d3e-8455-4991dc124ece

	measure 'Revenue per Product SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Revenue per Product], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: Product
		lineageTag: d99f0d92-0bd5-47c3-b151-c07402e977d0

	measure 'Revenue per Product Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Revenue per Product], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Product
		lineageTag: 79c8f327-1dd5-4f8a-a6a3-653de2ac4557

	measure 'Revenue per Product Arrow' = udf.adaptfy.svg.ragArrow( [Revenue per Product Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 8596545f-5b41-426e-a737-5d6c37e089cc
		dataCategory: ImageUrl

	measure 'Top Brand' =
			CALCULATE(
			    SELECTEDVALUE( DIM_Product[brand] ),
			    TOPN( 1, ALL( DIM_Product[brand] ), [Net Revenue], DESC )
			)
		displayFolder: Product
		lineageTag: a454a986-68f7-427b-978c-f6eea665c28f

	measure 'Discount Arrow' =
			VAR RawDelta    = [Discount Delta pp]
			VAR RoundedDelta = ROUND( RawDelta, 2 )
			RETURN
			    udf.adaptfy.svg.ragArrow( RoundedDelta, "INVERSE", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 9853dfb7-9b3e-4f2a-83ff-58d2f516ca7d
		dataCategory: ImageUrl

	measure 'New Customers' =
			CALCULATE(
			    DISTINCTCOUNT( FCT_Sales[customer_key] ),
			    FILTER(
			        VALUES( FCT_Sales[customer_key] ),
			        VAR FirstPurchaseDate =
			            CALCULATE( MIN( FCT_Sales[order_date] ), ALL( 'DIM_Date' ) )
			        RETURN
			            FirstPurchaseDate >= MIN( 'DIM_Date'[date] ) &&
			            FirstPurchaseDate <= MAX( 'DIM_Date'[date] )
			    )
			)
		formatString: #,0
		displayFolder: Customer
		lineageTag: 1a3bc347-9f57-45f2-afd7-d401f627cfbe

	measure 'Returning Customers' =
			CALCULATE(
			    DISTINCTCOUNT( FCT_Sales[customer_key] ),
			    FILTER(
			        VALUES( FCT_Sales[customer_key] ),
			        VAR FirstPurchaseDate =
			            CALCULATE( MIN( FCT_Sales[order_date] ), ALL( 'DIM_Date' ) )
			        RETURN
			            FirstPurchaseDate < MIN( 'DIM_Date'[date] )
			    )
			)
		formatString: #,0
		displayFolder: Customer
		lineageTag: aebaa99d-b1ea-436e-87af-1e0f765509c8

	measure 'New Customer %' = DIVIDE( [New Customers], [Customers] )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Customer
		lineageTag: c4b83ce5-e8d8-458f-b116-7a8e75f759a9

	measure 'Customers SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Customers], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: Customer
		lineageTag: f5a628f8-e9dd-4be9-955b-7efd254c088f

	measure 'Customers Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Customers], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Customer
		lineageTag: 3820c264-dcff-4ed3-811c-ff5dcf3ba1aa

	measure 'Customers Arrow' = udf.adaptfy.svg.ragArrow( [Customers Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 7a5b25b9-bcaf-4428-903c-30dc098b6701
		dataCategory: ImageUrl

	measure 'Revenue per Customer SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Revenue per Customer], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: Customer
		lineageTag: 0afd93bd-e736-4a7f-a005-b2c9edbc0f89

	measure 'Revenue per Customer Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Revenue per Customer], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Customer
		lineageTag: 4428cbc5-8dab-4698-9027-76da546f7a61

	measure 'Revenue per Customer Arrow' = udf.adaptfy.svg.ragArrow( [Revenue per Customer Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: a98e4d5f-77ad-45c2-9276-3ce0a7c30b77
		dataCategory: ImageUrl

	measure 'Repeat Rate SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Repeat Rate], 'dim_date'[date], "SPLY" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Customer
		lineageTag: bd85804a-3048-4dd1-8dba-a20efeceeedc

	measure 'Repeat Rate Delta pp' =
			VAR _TotalDates  = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = _TotalDates
			VAR RateNow      = [Repeat Rate]
			VAR RatePrior    = udf.adaptfy.timeintellgence( [Repeat Rate], 'dim_date'[date], "SPLY" )
			RETURN
			    IF(
			        _AllSelected,
			        0,
			        IF(
			            NOT ISBLANK( RateNow ) && NOT ISBLANK( RatePrior ),
			            ( RateNow - RatePrior ) * 100
			        )
			    )
		formatString: 0.00 "pp";-0.00 "pp";0.00 "pp"
		displayFolder: Customer
		lineageTag: e9891149-60ab-44f8-845b-bf892485a1de

	measure 'Repeat Rate Arrow' = udf.adaptfy.svg.ragArrow( [Repeat Rate Delta pp], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 22c46101-45a2-4c91-8f73-e3958262e8ec
		dataCategory: ImageUrl

	measure 'New Customers SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [New Customers], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: Customer
		lineageTag: 44759173-530c-419e-a9c7-2bb7ccebbb81

	measure 'New Customers Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [New Customers], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Customer
		lineageTag: 06ed9e25-3762-4be9-8df1-5383f6c25763

	measure 'New Customers Arrow' = udf.adaptfy.svg.ragArrow( [New Customers Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 22ae5584-3cd5-4f59-9367-d7b83932928e
		dataCategory: ImageUrl

	measure 'Average Age SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Average Age], 'dim_date'[date], "SPLY" ) )
		formatString: #,0.0
		displayFolder: Customer
		lineageTag: dfc8ead6-25c1-45b7-8938-b285e08344df

	measure 'Active Customers' = DISTINCTCOUNT( FCT_Sales[customer_key] )
		formatString: #,0
		displayFolder: Customer
		lineageTag: 2e0bb3f1-0fe3-47a4-8b2f-eb986267af8c

	measure 'Active Customers SPLY' =
			VAR _AllSelected = COUNTROWS( 'DIM_Date' ) = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			RETURN IF( _AllSelected, BLANK(), udf.adaptfy.timeintellgence( [Active Customers], 'dim_date'[date], "SPLY" ) )
		formatString: #,0
		displayFolder: Customer
		lineageTag: 6474976a-6651-4df3-b439-5172f53f0e32

	measure 'Active Customers Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Active Customers], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: Customer
		lineageTag: 0109585e-a2b1-4329-9cd2-2a83c424c66e

	measure 'Active Customers Arrow' = udf.adaptfy.svg.ragArrow( [Active Customers Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 50a66759-7ed6-445c-99d4-8eb27329f135
		dataCategory: ImageUrl

	measure 'Avg Order Value Arrow' = udf.adaptfy.svg.ragArrow( [Avg Order Value Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 6070cc31-25de-44b4-822a-047cc64a1814
		dataCategory: ImageUrl

	measure 'Avg Line Items Arrow' =
			VAR RoundedDelta = ROUND( [Avg Line Items Delta], 2 )
			RETURN
			    udf.adaptfy.svg.ragArrow( RoundedDelta, "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: f326c4ff-2b53-4026-85f7-71450c780ef4
		dataCategory: ImageUrl

	measure 'Line Items Delta %' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Line Items], 'dim_date'[date], "PCT" ) )
		formatString: 0.00%;-0.00%;0.00%
		displayFolder: KPI - Sales
		lineageTag: bf4b3589-4d4d-4797-acc3-5287e0fa8201

	measure 'Line Items Arrow' = udf.adaptfy.svg.ragArrow( [Line Items Delta %], "NORMAL", 48, "ARROW" )
		displayFolder: Formatting - Examples
		lineageTag: 13e35ebb-9909-44d9-ae50-765752484b10
		dataCategory: ImageUrl

	measure 'Avg Order Value Delta' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Avg Order Value], 'dim_date'[date], "DELTA" ) )
		formatString: #,0
		displayFolder: KPI - Time Intelligence
		lineageTag: a5033e90-e47e-4d7e-a8f4-4697b21a9011

	measure 'Avg Line Items Delta' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _AllSelected   = COUNTROWS( 'DIM_Date' ) = _TotalDates
			RETURN IF( _AllSelected, 0, udf.adaptfy.timeintellgence( [Avg Line Items], 'dim_date'[date], "DELTA" ) )
		formatString: #,0.00
		displayFolder: KPI - Time Intelligence
		lineageTag: 837e96e3-f268-4e60-bb69-8c55db5ae3a3

	measure 'Format string' =
			VAR __Value = ABS( SELECTEDMEASURE() )
			RETURN
			    SWITCH(
			        TRUE(),
			        ISBLANK( SELECTEDMEASURE() ), "",
			        SELECTEDMEASURE() = 0,        "#,0",
			        __Value >= 1E12,              "#,0,,,,.0T",
			        __Value >= 1E9,               "#,0,,,.0B",
			        __Value >= 1E6,               "#,0,,.0M",
			        __Value >= 1E3,               "#,0,.0K",
			        __Value >= 100,               "#,0",
			        __Value >= 10,                "#,0.0",
			        __Value >= 1,                 "#,0.00",
			                                      "#,0.000"
			    )
		displayFolder: KPI - Sales
		lineageTag: a4dd584b-f6d8-4593-b16d-1df627d45aae

	measure 'Selected Period vs SPLY' =
			VAR _TotalDates    = CALCULATE( COUNTROWS( 'DIM_Date' ), ALL( 'DIM_Date' ) )
			VAR _SelectedDates = COUNTROWS( 'DIM_Date' )
			VAR _AllSelected   = _SelectedDates = _TotalDates
			VAR _MinDate       = MIN( 'DIM_Date'[date] )
			VAR _MaxDate       = MAX( 'DIM_Date'[date] )
			VAR _MinSPLY       = DATE( YEAR( _MinDate ) - 1, MONTH( _MinDate ), DAY( _MinDate ) )
			VAR _MaxSPLY       = DATE( YEAR( _MaxDate ) - 1, MONTH( _MaxDate ), DAY( _MaxDate ) )
			VAR _SameMonth     = MONTH( _MinDate ) = MONTH( _MaxDate ) && YEAR( _MinDate ) = YEAR( _MaxDate )
			VAR _SameYear      = YEAR( _MinDate ) = YEAR( _MaxDate )
			VAR _Current =
			    IF( _SameMonth,
			        FORMAT( _MinDate, "MMM YYYY" ),
			        IF( _SameYear,
			            FORMAT( _MinDate, "MMM" ) & " - " & FORMAT( _MaxDate, "MMM YYYY" ),
			            FORMAT( _MinDate, "MMM YYYY" ) & " - " & FORMAT( _MaxDate, "MMM YYYY" )
			        )
			    )
			VAR _SPLY =
			    IF( _SameMonth,
			        FORMAT( _MinSPLY, "MMM YYYY" ),
			        IF( _SameYear,
			            FORMAT( _MinSPLY, "MMM" ) & " - " & FORMAT( _MaxSPLY, "MMM YYYY" ),
			            FORMAT( _MinSPLY, "MMM YYYY" ) & " - " & FORMAT( _MaxSPLY, "MMM YYYY" )
			        )
			    )
			RETURN
			    IF(
			        _AllSelected,
			        "All periods selected",
			        _Current & "  |  vs.  " & _SPLY
			    )
		displayFolder: KPI - Sales
		lineageTag: 46fbd696-dac1-4b4d-9926-0ee53235c9d6

	column dummy
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 23d209a0-adce-460a-b12c-0e432b612443
		summarizeBy: sum
		sourceColumn: dummy

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition _measures = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlCKjQUA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [dummy = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"dummy", Int64.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

