table FCT_Sales
	lineageTag: 94d3ea3b-4449-4e27-903d-c961f1df5413

	measure 'Net Revenue' =
			
			SUMX( FCT_Sales, FCT_Sales[quantity] * FCT_Sales[net_price] )
		formatString: #,0
		lineageTag: 7c5f9a14-3465-43ab-b1e5-aeb03f4fe8ad

		changedProperty = FormatString

	measure Cost =
			
			SUMX( FCT_Sales, FCT_Sales[quantity] * FCT_Sales[unit_cost] )
		formatString: #,0
		lineageTag: 416604ca-8ec2-48fb-97e3-568ef1a0c264

		changedProperty = FormatString

	measure 'Net Profit' =
			
			[Net Revenue] - [Cost]
		formatString: #,0
		lineageTag: e22dbc08-3844-485a-96d6-625d9d77e004

		changedProperty = FormatString

	measure 'Units Sold' =
			
			SUM( FCT_Sales[quantity] )
		formatString: #,0
		lineageTag: 3c59d762-8e5b-4258-a132-1b6983b435ce

		changedProperty = FormatString

	measure Orders =
			
			DISTINCTCOUNT( FCT_Sales[order_number] )
		formatString: #,0
		lineageTag: 4de0ade3-e121-4f05-a5d2-907ec49411a5

	measure 'Margin %' =
			
			DIVIDE( [Net Profit], [Net Revenue] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 78f2291d-1076-4202-b7bc-8d5dcd28f612

		changedProperty = FormatString

	column order_number
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 91ea6a29-4cac-4426-9100-5736937552bf
		summarizeBy: none
		sourceColumn: Order Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column line_number
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 45bd733b-90c9-4ecc-93d6-37528e2e27b4
		summarizeBy: none
		sourceColumn: Line Number

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column order_date
		dataType: dateTime
		isHidden
		formatString: mm/dd/yyyy
		lineageTag: 64b1d016-32bc-4c20-80d7-a5adc3b9ae88
		summarizeBy: none
		sourceColumn: Order Date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column delivery_date
		dataType: dateTime
		isHidden
		formatString: mm/dd/yyyy
		lineageTag: fb541e07-fdfb-40c9-9166-29777f049df4
		summarizeBy: none
		sourceColumn: Delivery Date

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column customer_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: b35afdc7-615a-4e88-8c36-36c10285f310
		summarizeBy: none
		sourceColumn: CustomerKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column store_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f917bacb-2013-409d-9d94-8b40068bc9a7
		summarizeBy: none
		sourceColumn: StoreKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column product_key
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: f011ea83-0d14-41e5-a9f2-8d532338586f
		summarizeBy: none
		sourceColumn: ProductKey

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column quantity
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: c8ca10d3-f54d-4c5d-b5ef-da854e2d7973
		summarizeBy: none
		sourceColumn: Quantity

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

	column unit_price
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 8c2ee660-1f97-48df-a30b-9e6818ed5be9
		summarizeBy: none
		sourceColumn: Unit Price

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column net_price
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 690e56a1-1bb6-4aa8-83bc-2b81fa8e4bf7
		summarizeBy: none
		sourceColumn: Net Price

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column unit_cost
		dataType: decimal
		isHidden
		formatString: #,0.00
		lineageTag: 07c65c15-9e35-47c1-bbab-9cca274818c7
		summarizeBy: none
		sourceColumn: Unit Cost

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	column currency_code
		dataType: string
		isHidden
		lineageTag: af1aa82f-8a7e-4d57-9da8-8d64994488a5
		summarizeBy: none
		sourceColumn: Currency Code

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isText":true}

	column exchange_rate
		dataType: double
		isHidden
		formatString: 0.0000
		lineageTag: 7ddca17e-170a-4c4d-aa29-37f19394e838
		summarizeBy: none
		sourceColumn: Exchange Rate

		changedProperty = IsHidden

		changedProperty = FormatString

		annotation SummarizationSetBy = User

	partition FCT_Sales-4929449f-be0b-48cf-a44e-c644698415ba = m
		mode: import
		source =
				let
				    Source = Sql.Databases("Demo"),
				    #"Contoso" = Source{[Name="Contoso V2 1M"]}[Data],
				    dbo_Sales = #"Contoso"{[Schema="dbo",Item="Sales"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_Sales,{{"Quantity", Int64.Type}, {"Unit Price", Currency.Type}, {"Net Price", Currency.Type}, {"Unit Cost", Currency.Type}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

